apiVersion: v1
kind: Secret
metadata:
  name: circleguard-secrets
  namespace: circleguard-prod
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "circleguard-password"
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: "password"
  LDAP_PASSWORD: "admin-password"
  JWT_SECRET: "your-secret-key-for-jwt-here-change-in-production"
  JWT_EXPIRATION: "86400"
