package com.circleguard.promotion.repository.graph;

import com.circleguard.promotion.model.graph.CircleNode;
import org.springframework.data.neo4j.repository.Neo4jRepository;
import org.springframework.data.neo4j.repository.query.Query;
import java.util.List;
import java.util.Optional;

public interface CircleNodeRepository extends Neo4jRepository<CircleNode, Long> {

    @Query("MATCH (c:Circle {inviteCode: $code}) RETURN c")
    Optional<CircleNode> findByInviteCode(String code);

    @Query("MATCH (u:User {anonymousId: $aid})-[r:MEMBER_OF]->(c:Circle) RETURN c")
    List<CircleNode> findCirclesByUser(String aid);

    @Query("MERGE (u:User {anonymousId: $aid}) " +
           "WITH u " +
           "MATCH (c:Circle {inviteCode: $code}) " +
           "MERGE (u)-[r:MEMBER_OF]->(c) " +
           "RETURN c")
    Optional<CircleNode> joinCircle(String aid, String code);
    
    @Query("MATCH (u1:User {anonymousId: $a1})-[:MEMBER_OF]->(c:Circle)<-[:MEMBER_OF]-(u2:User {anonymousId: $a2}) RETURN c")
    List<CircleNode> findCommonCircles(String a1, String a2);

    @Query("MATCH (u:User {anonymousId: $aid}), (c:Circle) WHERE id(c) = $circleId " +
           "MERGE (u)-[r:MEMBER_OF]->(c) " +
           "RETURN c")
    Optional<CircleNode> addUserToCircle(String aid, Long circleId);

    @Query("MATCH (u:User {anonymousId: $aid})-[:MEMBER_OF]->(c:Circle) " +
           "WHERE coalesce(c.isAutoGenerated, false) = false " +
           "MATCH (c)<-[:MEMBER_OF]-(m:User) " +
           "WITH c, collect(m.status) as statuses " +
           "WHERE all(s in statuses WHERE s IN ['SUSPECT', 'PROBABLE', 'CONFIRMED']) " +
           "RETURN c")
    List<CircleNode> findNewlyFencedCircles(String aid);

    boolean existsByInviteCode(String inviteCode);
}
