package com.circleguard.promotion.model.graph;

import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;
import lombok.*;
import java.util.*;

@Node("Circle")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CircleNode {
    @Id
    @GeneratedValue
    private Long id;

    private String name;
    private String inviteCode;
    private Long createdAt;
    private String locationId;
    @Builder.Default
    private Boolean isValid = true;
    @Builder.Default
    private Boolean forceFence = false;
    private Boolean isActive;
    private Boolean isAutoGenerated;

    @Relationship(type = "MEMBER_OF", direction = Relationship.Direction.INCOMING)
    @Builder.Default
    private Set<UserNode> members = new HashSet<>();
}
