package com.circleguard.promotion.service;

import com.circleguard.promotion.model.graph.CircleNode;
import com.circleguard.promotion.repository.graph.CircleNodeRepository;
import com.circleguard.promotion.repository.graph.UserNodeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
public class AutoCircleService {

    private final UserNodeRepository userRepository;
    private final CircleNodeRepository circleRepository;
    private final CircleService circleService;

    // Threshold: 1 hour (3600 seconds) of cumulative duration
    private static final long AUTO_THRESHOLD_SECONDS = 3600;

    /**
     * Analyzes encounters between two users and elevates to a safety circle if high-trust is detected.
     * This runs asynchronously to maintain high throughput for encounter reporting.
     */
    @Async
    @Transactional("neo4jTransactionManager")
    public void evaluateEncounter(String a1, String a2) {
        if (a1 == null || a2 == null || a1.equals(a2)) return;

        Long duration = userRepository.getCumulativeEncounterDuration(a1, a2);
        if (duration != null && duration >= AUTO_THRESHOLD_SECONDS) {
            
            // Check if they are already in an auto-generated circle together
            boolean alreadyConnected = circleRepository.findCommonCircles(a1, a2).stream()
                .anyMatch(c -> Boolean.TRUE.equals(c.getIsAutoGenerated()));

            if (!alreadyConnected) {
                log.info("High-trust encounter detected between {} and {}. Elevating to automated safety mesh.", a1, a2);
                
                CircleNode autoCircle = CircleNode.builder()
                    .name("Auto Mesh " + UUID.randomUUID().toString().substring(0, 4).toUpperCase())
                    .inviteCode("AUTO-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase())
                    .isActive(true)
                    .isAutoGenerated(true)
                    .createdAt(System.currentTimeMillis())
                    .build();

                circleRepository.save(autoCircle);
                
                // Join both users
                circleService.joinCircle(a1, autoCircle.getInviteCode());
                circleService.joinCircle(a2, autoCircle.getInviteCode());
                
                log.info("System-managed safety mesh established: {}", autoCircle.getInviteCode());
            }
        }
    }
}
